#
# GPL                                                                        
# (c) 2015, thorsten.johannvorderbrueggen@t-online.de                        
#

.PHONY: all clean

all:
	@echo "Nothing to do -> only cleaning"

clean:
	rm -f *~
	rm -f *~
	rm -f math_functions/*~
	rm -f math_functions/.*~
	rm -rf build
	rm -rf _build

distclean: clean
