.\" Manpage for baalued
.\" Contact thorsten.johannvorderbrueggen@t-online.de to correct errors or typos.
.TH baalued 1 "11 Oct 2015" "0.0.1" "baalued man page"
.SH NAME
baalued
\-\- the baalued
.SH SYNOPSIS
.PP
.SH DESCRIPTION
This functions are part of the
.BR baalue_sdk
(https://github.com/tjohann/baalued)
.PP
The baalue daemon
.PP
.SH FILES
.BR baalued.c
\- function implementation
.br
.BR baalued.h
\- interface header
.br
.PP
.SH OPTIONS
None
.PP
.SH BUGS
No known bugs
.PP
.SH "SEE ALSO"
.BR baalue(1)
.PP
.BR libbaalue(3)
.PP
.SH AUTHOR
Thorsten Johannvorderbrueggen
.br
Email: \fB<thorsten.johannvorderbrueggen@t-online.de> \fP

